# Generated by Django 4.2.7 on 2023-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityNews__main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the fact', max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Description of the fact', max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
