# Generated by Django 4.2.7 on 2023-11-12 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CityNews__main', '0002_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the News & Article', max_length=255, verbose_name='Title')),
                ('author', models.CharField(default='Anonymous', help_text='Author of the News & Article', max_length=255, verbose_name='Author')),
                ('tags', models.CharField(blank=True, help_text='Tags for the News & Article', max_length=50, null=True, verbose_name='Tags')),
                ('publish_date', models.DateField(help_text='Publish date of the News & Article', verbose_name='Publish date')),
                ('description', models.TextField(help_text='Main content of the News & Article', max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityNews__main.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment', max_length=1000, verbose_name='Comment')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='Publish date of the comment', verbose_name='Publish date')),
                ('article', models.ForeignKey(help_text='Commented article', on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='CityNews__main.newsarticle', verbose_name='Comment - Article')),
                ('author', models.ForeignKey(help_text='Author of the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Comment - Author')),
            ],
        ),
    ]
