# Generated by Django 4.2.7 on 2023-11-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityNews__main', '0003_newsarticle_savedarticle_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-publish_date'], 'verbose_name_plural': 'News & Articles'},
        ),
        migrations.AlterModelOptions(
            name='savedarticle',
            options={'verbose_name_plural': 'Saved Articles'},
        ),
    ]
