# Generated by Django 4.2.7 on 2023-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityNews__main', '0004_alter_newsarticle_options_alter_savedarticle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, help_text='Publish date of the comment', verbose_name='Publish date'),
        ),
    ]
